<div class="hero-unit">
<?php

$title = 'My images';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('image', array('action'=>'add'));?>">Add new image</a>
</p>
<div>


<?php foreach ($images as $image) : ?>
    	
    	<img alt="<?php echo $this->escapeHtml($image->title);?>" src="../../../<?php echo $this->escapeHtml($image->src);?>" style="width: 300px; margin:10px;">
    	<a href="<?php echo $this->url('image',
                    array('action' => 'delete', 'id' => $image->id));?>">X</a>
<?php endforeach; ?>
</div>
</div>